extends RigidBody2D


@export var min_speed = 150.0
@export var max_speed = 250.0 
@onready var animated_sprite = $AnimatedSprite2D

func _ready():
	#This function randomizes the pseudo-random number generated by randi()
	#In every execution
	var mob_types = animated_sprite.sprite_frames.get_animation_names()
	#the remainder of the division of a random number by the size of mob_types will
	#always be at most equal to size-1
	animated_sprite.play(mob_types[randi() % mob_types.size()])
	

func _on_visible_on_screen_notifier_2d_screen_exited():
	#This function frees the spawned mob from the program's memory once the mob
	#leaves the screen, which activates the notifier's "2d screen exited" signal
	queue_free()
